### ISSUE TITLE
Separation of data

### ISSUE THREAD

**Issue by tapishr** [Alokit-Innovations/dev-profiler#25]
Dod -
- Schema/db design for keeping data for now
- pipelines to sync/run jobs

**Comment by tapishr** [comment]
Gsuite id can be used as primary id for recognising orgs
User schema
- our generated id
- role (em/dev)
- auth_info (json)
- aliases [array]
- orgs [array]
- name
- photo
- code hosting site id/url
- socials (urls)

**Comment by tapishr** [comment]
Repo schema - 
- id
- name
- users/aliases [array]
- repo_git_url
- metadata (json)
- auth_info

**Comment by tapishr** [comment]
Postgres schemas for all entities

**Comment by tapishr** [comment]
- [ ] Create user schema, access to write to table, read from table
- [ ] Create repo schema, access to write to table, read from table
- [ ] Save queries in git

When user logs in -
- [ ] On login, check for existing orgs/repos. If not, create new table, user specific to org from cloudrun
- [ ] Push user row in table ftue
- [ ] Update user table when its field values change (on every login?)
- [ ] Fetch all repos for a user

**Comment by tapishr** [comment]
user table created, repo table created, access to be given, roles created. explored redis, not usable right now, development speed slow due to complex data structure.

**Comment by tapishr** [comment]
`superuser` role given to the website user, able to perform joins, yet to test without write permissions. Indexing permissions to be handled by admin users `postgres` and `tapish`. Created query for push table ftue and login ftue and tested login with dummy data. Need to ask about storing in git - new repo or cloudrun?

**Comment by tapishr** [comment]
PR raised with all tasks done

**Comment by avikalpg** [comment]
Change name of column `profile_url` to `photo_url`

**Comment by avikalpg** [comment]
Org schema:

1. id
2. Name
3. Members

**Comment by avikalpg** [comment]
remove `org` and `role` from `users` table.

**Comment by tapishr** [comment]
Created a second user table (@muskan) to store github and bitbucket specific tokens and repos

**Comment by tapishr** [comment]
Created [issue 51](https://github.com/Alokit-Innovations/devprofiler-cloudrun/issues/51)  to track pipelines to sync data. Closing this ticket
